version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123123
      MYSQL_DATABASE: todo
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build:
      context: ./todo-list-backend
    container_name: backend
    restart: always
    env_file:
      - ./todo-list-backend/.env
    environment:
      DATABASE_URL: mysql://root:123123@mysql:3306/todo
      PORT: 4000
      ALLOWED_ORIGIN: http://localhost:3000
    ports:
      - "4000:4000"
    depends_on:
      - mysql
    command: >
      sh -c "
      npx prisma migrate deploy &&
      npm run start:prod
      "

  frontend:
    build:
      context: ./todo-list-frontend
    container_name: frontend
    restart: always
    env_file:
      - ./todo-list-frontend/.env
    environment:
      NEXT_PUBLIC_SERVER_URL: http://localhost:4000
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mysql_data:
